name: Docker release

on:
  pull_request:
    branches:
      - main-enterprise
    types:
      - closed
    paths-ignore:
      - LICENSE
      - README.md
      - .github/**
      - .*
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions: write-all

jobs:
  image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    #   packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: echo ${{ github.actor }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag if needed
        id: tag
        run: |
          if [[ ${{ github.ref_type }} == "tag" ]]; then 
            VERSION=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\///g')
          else
            LAST_TAG=$(git tag --sort=creatordate --sort=v:refname | tail -n1)
            VERSION=$(echo "$LAST_TAG" | awk '{split(substr($0, 2), a, "."); printf "v%d.%d.%d", a[1], a[2], a[3]+1}')
            git tag $VERSION
            git push --tags
          fi
          echo "::set-output name=version::$VERSION"

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

      - name: What
        run: |
          echo "LABELS: ${{ steps.meta.outputs.labels }}"
          echo "VERSION: ${{ steps.tag.outputs.version }}"
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64